export const Filter = [
  {
    id: 1,
    Name: "Brand",
    subtitle: "80 available",
    Sub: [
      "Agent Nateur",
      "Alpyn Beauty",
      "Augustinus Bader",
      "Avène",
      "Beautyblender",
      "Beneath Your Mask",
      "Bloomeffects",
      "Bluemercury",
      "Bobbi Brown",
      "BY TERRY",
      "Caudalie",
      "Chantecaille",
      "Clarins",
      "Clinique",
      "Costa Brazil",
      "Deborah Lippmann",
      "Dermalogica",
      "Dr. Barbara Sturm",
      "Estée Lauder",
      "Fresh",
      "Fur",
      "Furtuna Skin",
      "HATCH Mama",
      "Hourglass",
      "Indie Lee",
      "IS CLINICAL",
      "Jack Black",
      "Jane Iredale",
      "Jillian Dempsey",
      "Jo Malone London",
      "Juice Beauty",
      "Kevyn Aucoin",
      "Kiehl's Since 1851",
      "Kjaer Weis",
      "KLORANE",
      "KNC",
      "Kosas",
      "La Mer",
      "Lash Star",
      "LASHFOOD",
      "Laura Mercier",
      "Lilah B",
      "Lune+Aster",
      "M-61",
      "Mara",
      "Mario Badescu",
      "Maya Chia",
      "Nailmatic",
      "Nannette De Gaspé",
      "NARS",
      "Natura Bissé",
      "Naturopathica",
      "Odacité",
      "One Love Organics",
      "Oribe",
      "OSEA",
      "Patchology",
      "PCA Skin",
      "Peter Thomas Roth",
      "Philip Kingsley",
      "PHYTO",
      "Retrouvé",
      "RMS Beauty",
      "Rodial",
      "RÓEN BEAUTY",
      "Sisley-Paris",
      "SK-I",
      "SkinCeuticals",
      "Skyn ICELAND",
      "Smith & Cult",
      "Supergoop!",
      "Surratt",
      "Tata Harper",
      "Teami",
      "The Beauty Chef",
      "This Works",
      "Tom Ford",
      "Trish McEvoy",
      "Wander Beauty",
    ],
  },
  {
    id: 2,
    Name: "Coverage",
    subtitle: "8 available",
    Sub: [
      "Buildable",
      "Full",
      "Light",
      "Light-Medium",
      "Medium",
      "Medium-Full",
      "Sheer",
      "Sheer-Light",
    ],
  },
  {
    id: 3,
    Name: "Finish",
    subtitle: "15 available",
    Sub: [
      "Creme",
      "Dewy",
      "High Shine",
      "Iridescent",
      "Matte",
      "Metallic",
      "Natural",
      "Radiant",
      "Satin",
      "Satin-Matte",
      "Semi-Matte",
      "Semi-Sheer",
      "Sheer",
      "Shimmer",
      "Shine",
    ],
  },
  {
    id: 4,
    Name: "Benefit",
    subtitle: "35 available",
    Sub: [
      "Anti-Aging",
      "Anti-Pollution",
      "Blue Light Protection",
      "Brightening",
      "Color Enhancing",
      "Color-Correcting",
      "Curl Enhancing",
      "Detox",
      "Exfoliating",
      "Fast Drying",
      "Firming",
      "For Blondes",
      "For Brunettes",
      "For Red Hair",
      "Fullness",
      "Gloss And Shine",
      "Gut Health And Digestion",
      "Hold",
      "Hydrating",
      "Lengthening",
      "Long Lasting",
      "Oil Control",
      "Prenatal",
      "Sleep Aid",
      "Smoothing",
      "Smudge-Proof",
      "Strengthening",
      "Stress Relief",
      "Thickening",
      "Transfer Resistant",
      "Transfer-Proof",
      "Volume And Texture",
      "Volumizing",
      "Waterproof",
    ],
  },
  {
    id: 5,
    Name: "Concern",
    subtitle: "24 available",
    Sub: [
      "Acne And Blemishes",
      " Black Heads And Visible Pores",
      "Breakage",
      "Dark Circles",
      "Dark Spots",
      "Dry Lips",
      "Dryness",
      "Dullness",
      "Fine Lines",
      "Fine Lines And Wrinkles",
      "Free Radicals",
      "Hair Loss And Thinning",
      "Ingrown Hair",
      "Loss Of Firmness",
      "Oily Skin",
      "Oily Spots",
      "Puffiness",
      "Razor Burn",
      "Redness",
      "Redness And Irritation",
      "Rough / Bumpy Skin",
      "Scars And Discoloration",
      "Sun Damage",
    ],
  },
  {
    id: 6,
    Name: "Ingredient Preference",
    subtitle: "32 available",
    Sub: [
      "Allergy Tested",
      "Antioxidants",
      "Biotin",
      "Cbd",
      "Ceramides",
      "Charcoal",
      "Collagen",
      "Dermatologist Tested",
      "Formaldehyde Free",
      "Fragrance Free",
      "Gluten Free",
      "Hyaluronic Acid",
      "Hypoallergenic",
      "Mindful Ingredients",
      "Mineral",
      "Naturally Derived",
      "Niacinamide",
      "Oil-Free",
      "Organic",
      "Paraben Free",
      "Peptides",
      "Phthalates Free",
      "Plant Stem Cells",
      "Probiotics",
      "Salicylic Acid",
      "Shea Butter",
      "Silicone Free",
      "Sulfate Free",
      "Vegan And Cruelty Free",
      "Vitamin B5",
      "Vitamin C",
      "Vitamin E",
    ],
  },
  {
    id: 7,
    Name: "Formulation",
    subtitle: "18 available",
    Sub: [
      "Balm",
      "Bar",
      "Cream",
      "Cream Powder",
      "Gel",
      "Gloss",
      "Liquid",
      "Loose Powder",
      "Oil",
      "Pencil",
      "Pill",
      "Powder",
      "Pressed Powder",
      "Spray",
      "Stain",
      "Stick",
      "Tablet",
      "Towelette",
    ],
  },
  {
    id: 8,
    Name: "Bristle Type",
    subtitle: "2 available",
    Sub: ["Natural", "Synthetic"],
  },
  {
    id: 9,
    Name: "Color Family",
    subtitle: "19 available",
    Sub: [
      "Berry",
      "Black",
      "Blue",
      "Bronze",
      "Brown",
      "Clear",
      "Coral",
      "Gold",
      "Gray",
      "Green",
      "Multi",
      "Nude",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Silver",
      "White",
      "Yellow",
    ],
  },
  {
    id: 10,
    Name: "Spf",
    subtitle: "4 available",
    Sub: ["6 To 30", "31 To 49", "5 To 15", "50+"],
  },
  {
    id: 11,
    Name: "Size",
    subtitle: "2 available",
    Sub: ["Jumbo And Value Size", "Travel Size"],
  },
  {
    id: 12,
    Name: "More Ways To Shop",
    subtitle: "9 available",
    Sub: [
      "Asian- And Pacific Islander-Founded",
      "Award Winners",
      "Black-Founded",
      "Conscious Beauty",
      "Exclusive",
      "Hispanic- And Latino-Founded",
      "Limited Edition",
      "Sustainable",
      "Women-Founded",
    ],
  },
  {
    id: 13,
    Name: "Price",
    subtitle: "5 available",
    Sub: [
      "$0 To $50",
      "$50 To $100",
      "$100 To $200",
      "$200 To $300",
      "$300 To $500",
    ],
  },
];
