export const ADD_ADDRESS_REQUEST="ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS="ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAILURE="ADD_ADDRESS_FAILURE"


export const GET_ADDRESS_REQUEST="GET_ADDRESS_REQUEST"
export const GET_ADDRESS_SUCCESS="GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FALIURE="GET_ADDRESS_FALIURE"