export const ADD_TOCART_REQUEST="ADD_TOCART_REQUEST"
export const ADD_TOCART_SUCCESS="ADD_TOCART_SUCCESS"
export const ADD_TOCART_FAILURE="ADD_TOCART_FAILURE"

export const GET_CART_REQUEST="GET_CART_REQUEST"
export const GET_CART_SUCCESS="GET_CART_SUCCESS"
export const GET_CART_FALIURE="GET_CART_FALIURE"

export const DELETE_FROM_CART="DELETE_FROM_CART"