export const ADD_TO_WISH_LIST_REQUEST = "ADD_TO_WISH_LIST_REQUEST"
export const ADD_TO_WISH_LIST_SUCCESS = "ADD_TO_WISH_LIST_SUCCESS"
export const ADD_TO_WISH_LIST_FAILURE = "ADD_TO_WISH_LIST_FAILURE"